services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # <--- ВОТ ГЛАВНОЕ ИСПРАВЛЕНИЕ
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
    name: dikorosua_postgres_data
